# ... APIGateway Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apigateway
    spec:
      containers:
        - image: {{ .Values.image.gateway.repository }}:{{ .Values.image.tag }}
          name: apigateway
          ports:
            - containerPort: {{ .Values.service.gateway.port }}