# ... Profile Service Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: profile
  name: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: profile
    spec:
      containers:
        - image: {{ .Values.image.profile.repository }}:{{ .Values.image.tag }}
          name: profile
          ports:
            - containerPort: {{ .Values.service.profile.port }}
          volumeMounts:
            - name: datasource
              mountPath: {{ .Values.volume.mountPathContainer }}
      volumes:
        - name: datasource
          hostPath:
            path: {{ .Values.volume.hostPath }}

