# ... Stream Service Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stream
  name: stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stream
    spec:
      containers:
        - image: {{ .Values.image.stream.repository }}:{{ .Values.image.tag }}
          name: stream
          ports:
            - containerPort: {{ .Values.service.stream.port }}
          volumeMounts:
            - name: datasource
              mountPath: {{ .Values.volume.mountPathContainer }}
      volumes:
        - name: datasource
          hostPath:
            path: {{ .Values.volume.hostPath }}
